stages:
  ingest:
    cmd: python src/data/ingest.py
    deps:
      - src/data/ingest.py
      - data/raw/crop_yield.csv
    params:
      - data.raw_file
    outs:
      - data/interim/cleaned_data.csv

  test_data:
    cmd: pytest src/data/test_data.py
    deps:
      - src/data/test_data.py
      - data/raw/crop_yield.csv
      - data/raw/crop_yield.csv

  analyze:
    cmd: python src/visualization/analyze.py
    deps:
      - src/visualization/analyze.py
      - data/interim/cleaned_data.csv
    outs:
      - reports/figures/
      - reports/eda_summary.txt

  preprocess:
    cmd: python src/features/preprocess.py
    deps:
      - src/features/preprocess.py
      - data/interim/cleaned_data.csv
    params:
      - data.drop_cols
      - base.test_size
      - base.random_state
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
      - data/processed/preprocessor.pkl
      - data/processed/columns.pkl

  train_evaluate:
    cmd: python src/models/train_evaluate.py
    deps:
      - src/models/train_evaluate.py
      - data/processed/train.csv
      - data/processed/test.csv
      - data/processed/test.csv
    outs:
      - models/best_model.pkl
      - reports/model_comparison.csv
