base:
  project: crop_yield_prediction
  random_state: 42
  test_size: 0.2

data:
  raw_file: data/raw/crop_yield.csv
  processed_dir: data/processed
  train_file: data/processed/train.csv
  test_file: data/processed/test.csv
  target_col: Yield
  cat_cols:
    - Crop
    - Season
    - State
  drop_cols:
    - Area
    - Production
    - Crop_Year

train:
  model_type: gradient_boosting
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 3
